# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process.trade.interface <- function(opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays) {
    .Call('btutils_processTradeInterface', PACKAGE = 'btutils', opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays)
}

process.trades.interface <- function(ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn) {
    .Call('btutils_processTradesInterface', PACKAGE = 'btutils', ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn)
}

trades.from.signal.interface <- function(sigIn) {
    .Call('btutils_tradesFromSignalInterface', PACKAGE = 'btutils', sigIn)
}

get.returns.interface <- function(ibegIn, iendIn, positionIn, returnsIn) {
    .Call('btutils_getReturnsInterface', PACKAGE = 'btutils', ibegIn, iendIn, positionIn, returnsIn)
}

