# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cap.trade.duration.interface <- function(indicatorIn, shortDurationCap, longDurationCap) {
    .Call('btutils_capTradeDurationInterface', PACKAGE = 'btutils', indicatorIn, shortDurationCap, longDurationCap)
}

process.trade.interface <- function(opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays) {
    .Call('btutils_processTradeInterface', PACKAGE = 'btutils', opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays)
}

process.trades.interface <- function(ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn) {
    .Call('btutils_processTradesInterface', PACKAGE = 'btutils', ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn)
}

trades.from.indicator.interface <- function(indicatorIn) {
    .Call('btutils_tradesFromIndicatorInterface', PACKAGE = 'btutils', indicatorIn)
}

filter.returns.interface <- function(returnsIn, ibegIn, iendIn, positionIn) {
    .Call('btutils_filterReturnsInterface', PACKAGE = 'btutils', returnsIn, ibegIn, iendIn, positionIn)
}

