// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// capTradeDurationInterface
Rcpp::NumericVector capTradeDurationInterface(SEXP indicatorIn, int shortDurationCap, int longDurationCap);
RcppExport SEXP btutils_capTradeDurationInterface(SEXP indicatorInSEXP, SEXP shortDurationCapSEXP, SEXP longDurationCapSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type indicatorIn(indicatorInSEXP );
        Rcpp::traits::input_parameter< int >::type shortDurationCap(shortDurationCapSEXP );
        Rcpp::traits::input_parameter< int >::type longDurationCap(longDurationCapSEXP );
        Rcpp::NumericVector __result = capTradeDurationInterface(indicatorIn, shortDurationCap, longDurationCap);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// processTradeInterface
Rcpp::List processTradeInterface(SEXP opIn, SEXP hiIn, SEXP loIn, SEXP clIn, int ibeg, int iend, int pos, double stopLoss, double stopTrailing, double profitTarget, int maxDays);
RcppExport SEXP btutils_processTradeInterface(SEXP opInSEXP, SEXP hiInSEXP, SEXP loInSEXP, SEXP clInSEXP, SEXP ibegSEXP, SEXP iendSEXP, SEXP posSEXP, SEXP stopLossSEXP, SEXP stopTrailingSEXP, SEXP profitTargetSEXP, SEXP maxDaysSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type opIn(opInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type hiIn(hiInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type loIn(loInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type clIn(clInSEXP );
        Rcpp::traits::input_parameter< int >::type ibeg(ibegSEXP );
        Rcpp::traits::input_parameter< int >::type iend(iendSEXP );
        Rcpp::traits::input_parameter< int >::type pos(posSEXP );
        Rcpp::traits::input_parameter< double >::type stopLoss(stopLossSEXP );
        Rcpp::traits::input_parameter< double >::type stopTrailing(stopTrailingSEXP );
        Rcpp::traits::input_parameter< double >::type profitTarget(profitTargetSEXP );
        Rcpp::traits::input_parameter< int >::type maxDays(maxDaysSEXP );
        Rcpp::List __result = processTradeInterface(opIn, hiIn, loIn, clIn, ibeg, iend, pos, stopLoss, stopTrailing, profitTarget, maxDays);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// processTradesInterface
Rcpp::List processTradesInterface(SEXP ohlcIn, SEXP ibegsIn, SEXP iendsIn, SEXP positionIn, SEXP stopLossIn, SEXP stopTrailingIn, SEXP profitTargetIn, SEXP maxDaysIn);
RcppExport SEXP btutils_processTradesInterface(SEXP ohlcInSEXP, SEXP ibegsInSEXP, SEXP iendsInSEXP, SEXP positionInSEXP, SEXP stopLossInSEXP, SEXP stopTrailingInSEXP, SEXP profitTargetInSEXP, SEXP maxDaysInSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type ohlcIn(ohlcInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ibegsIn(ibegsInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type iendsIn(iendsInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type positionIn(positionInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type stopLossIn(stopLossInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type stopTrailingIn(stopTrailingInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type profitTargetIn(profitTargetInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type maxDaysIn(maxDaysInSEXP );
        Rcpp::List __result = processTradesInterface(ohlcIn, ibegsIn, iendsIn, positionIn, stopLossIn, stopTrailingIn, profitTargetIn, maxDaysIn);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// tradesFromIndicatorInterface
Rcpp::List tradesFromIndicatorInterface(SEXP indicatorIn);
RcppExport SEXP btutils_tradesFromIndicatorInterface(SEXP indicatorInSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type indicatorIn(indicatorInSEXP );
        Rcpp::List __result = tradesFromIndicatorInterface(indicatorIn);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// filterReturnsInterface
Rcpp::NumericVector filterReturnsInterface(SEXP returnsIn, SEXP ibegIn, SEXP iendIn, SEXP positionIn);
RcppExport SEXP btutils_filterReturnsInterface(SEXP returnsInSEXP, SEXP ibegInSEXP, SEXP iendInSEXP, SEXP positionInSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type returnsIn(returnsInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type ibegIn(ibegInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type iendIn(iendInSEXP );
        Rcpp::traits::input_parameter< SEXP >::type positionIn(positionInSEXP );
        Rcpp::NumericVector __result = filterReturnsInterface(returnsIn, ibegIn, iendIn, positionIn);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
